### ISSUE TITLE
unnecessary print in plot ?

### ISSUE THREAD

**Issue by ggrrll** [jaidevd/pyhht#50]
Hi, 

is printing this info really needed ?
https://github.com/jaidevd/pyhht/blob/61af178a969730064b257af020f3154b123fc552/pyhht/visualization.py#L80

- it makes it difficult to save the plot for instance ....
- also, is that correct? I am bit confused by `i + 2` ?   isn't `i+1` -- anyway, better to remove I guess

**Comment by jaidevd** [comment]
Hi @ggrrll ,

Yes, that line is unnecessary, removing it.

When you're making [subplots with matplotlib](https://matplotlib.org/api/_as_gen/matplotlib.pyplot.subplot.html), the signature of the subplots is as follows:
```python
subplot(nrows, ncols, index, **kwargs)
```
where `index` starts from 1, unlike usual Python indices. In the loop that plots IMFs, the iteration variable `i` starts from 0. Secondly, when plotting IMFs, the top row is reserved for the original signal. So that means:
1. We cannot have `i = 0` in the subplot command
2. The first row is already taken
3. The `i`th IMF should come at the `i + 2`th place in the subplots.

That's where the `i + 2` comes from.

Please see: b5e15b9fb372dc1a97fa87e9d828c8f2c6597700
